-- 프로모터스 분석 정제 규칙 및 개인정보 보호
begin;

create table if not exists public.analytics_exclusion_rules (
  id bigint generated by default as identity primary key,
  rule_type text not null check (rule_type in ('ua_contains', 'ip_cidr', 'host_allow')),
  rule_value text not null,
  label text not null default '',
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (rule_type, rule_value)
);

alter table public.analytics_exclusion_rules enable row level security;

insert into public.analytics_exclusion_rules(rule_type, rule_value, label) values
  ('host_allow', 'www.promotors.kr', '운영 도메인'),
  ('ua_contains', 'bot', '자동 수집기'),
  ('ua_contains', 'crawler', '자동 수집기'),
  ('ua_contains', 'spider', '자동 수집기'),
  ('ua_contains', 'slurp', '자동 수집기'),
  ('ua_contains', 'bingbot', 'Bing'),
  ('ua_contains', 'googlebot', 'Google'),
  ('ua_contains', 'yeti', 'Naver'),
  ('ua_contains', 'facebookexternalhit', 'Facebook'),
  ('ua_contains', 'headlesschrome', '자동 브라우저'),
  ('ip_cidr', '40.77.0.0/16', 'Bing'),
  ('ip_cidr', '157.55.0.0/16', 'Bing'),
  ('ip_cidr', '66.249.0.0/16', 'Google'),
  ('ip_cidr', '218.152.163.197/32', '내부 테스트 의심 IP')
on conflict (rule_type, rule_value) do nothing;

create or replace function public.pm_activity_read_v2(
  p_token text,
  p_from timestamptz,
  p_to timestamptz,
  p_limit integer default 10000
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  developer_ok boolean;
  result jsonb;
  safe_from timestamptz;
  safe_to timestamptz;
begin
  select coalesce(bool_or(a.profile->>'developer' = 'true'), false)
  into developer_ok
  from public.pm_sessions s
  join public.pm_accounts a on a.login_id = s.login_id
  where s.token_hash = public.pm_token_hash(p_token)
    and s.expires_at > now()
    and a.active;

  if not developer_ok then
    raise exception 'DEVELOPER_REQUIRED' using errcode = 'P0001';
  end if;

  safe_from := greatest(coalesce(p_from, now() - interval '30 days'), now() - interval '90 days');
  safe_to := least(coalesce(p_to, now()), now() + interval '1 day');
  if safe_from >= safe_to then
    raise exception 'INVALID_DATE_RANGE' using errcode = 'P0001';
  end if;

  select coalesce(jsonb_agg(to_jsonb(q)), '[]'::jsonb)
  into result
  from (
    select
      l.id,
      l.event_type,
      l.payload,
      l.page_url,
      case
        when l.ip_address is null then null
        when family(l.ip_address) = 4 then regexp_replace(host(l.ip_address), '\.[0-9]+$', '.*')
        else split_part(host(l.ip_address), ':', 1) || ':*'
      end as ip_address,
      l.visitor_key,
      null::text as user_agent,
      l.referrer,
      l.member_id,
      l.actor_role,
      l.created_at
    from public.site_logs l
    where l.created_at >= safe_from
      and l.created_at < safe_to
      and not exists (
        select 1
        from public.analytics_exclusion_rules r
        where r.enabled
          and (
            (r.rule_type = 'ua_contains' and lower(coalesce(l.user_agent, '')) like '%' || lower(r.rule_value) || '%')
            or (r.rule_type = 'ip_cidr' and l.ip_address is not null and l.ip_address <<= r.rule_value::cidr)
          )
      )
      and coalesce(substring(l.page_url from 'https?://([^/]+)'), '') in (
        select rule_value
        from public.analytics_exclusion_rules
        where enabled and rule_type = 'host_allow'
      )
    order by l.created_at desc
    limit least(greatest(coalesce(p_limit, 10000), 1), 10000)
  ) q;

  return result;
end
$$;

revoke all on table public.analytics_exclusion_rules from public, anon, authenticated;
revoke all on function public.pm_activity_read_v2(text, timestamptz, timestamptz, integer) from public;
grant execute on function public.pm_activity_read_v2(text, timestamptz, timestamptz, integer) to anon, authenticated;

notify pgrst, 'reload schema';
commit;
